# Generated by Django 2.2.5 on 2020-07-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cont_no', models.IntegerField()),
                ('addr', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('rice', models.FloatField()),
                ('daal', models.FloatField()),
                ('salt', models.FloatField()),
                ('amnt', models.FloatField()),
            ],
        ),
    ]
