# Generated by Django 2.2.5 on 2020-07-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='addr',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='amnt',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
