# Generated by Django 2.2.5 on 2020-07-10 06:46

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200710_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='address',
            field=models.CharField(help_text='Deleivery Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='cont_no',
            field=models.CharField(help_text='Contact Phone Number', max_length=31),
        ),
        migrations.AlterField(
            model_name='details',
            name='daal',
            field=models.FloatField(verbose_name='Amount of Daal'),
        ),
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(help_text='Customer Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='rice',
            field=models.FloatField(help_text='Amount of Rice'),
        ),
        migrations.AlterField(
            model_name='details',
            name='salt',
            field=models.FloatField(verbose_name='Amount of Salt'),
        ),
    ]
