# Generated by Django 2.2.5 on 2020-07-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200710_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='cont_no',
            field=models.CharField(help_text='Contact Phone Number', max_length=12),
        ),
    ]
