# Generated by Django 3.0.6 on 2020-07-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200710_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='address',
            field=models.CharField(help_text='Delivery Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='daal',
            field=models.FloatField(help_text='Amount of Daal in kg'),
        ),
        migrations.AlterField(
            model_name='details',
            name='rice',
            field=models.FloatField(help_text='Amount of Rice in kg'),
        ),
        migrations.AlterField(
            model_name='details',
            name='salt',
            field=models.FloatField(help_text='Amount of Salt in kg'),
        ),
    ]
