# Generated by Django 3.0.6 on 2020-07-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200711_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='time',
            field=models.TimeField(),
        ),
    ]
